name: develop
#Triggers
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
#Functions
jobs:
  #Build Job
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Check eslint
        run: npm run lint:fix
      - name: Build Project
        run: npm run build-storybook
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./storybook-static
